#!/bin/bash

echo "Building the application..."

# install dependencies and build the application
npm install && npm build

echo "Copying assets to be served..."

# copy the stuff that should be served to the root folder
mv dist       www/dist
mv index.html www/index.html
