'use strict';

/**
 * Defines 'action' constants.
 */
module.exports = {
	LOAD_TICKETS:         'LOAD_TICKETS',
	LOAD_TICKETS_SUCCESS: 'LOAD_TICKETS_SUCCESS',
	LOAD_TICKETS_FAILURE: 'LOAD_TICKETS_FAILURE',

	LOAD_USER:         'LOAD_USER',
	LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS',
	LOAD_USER_FAILURE: 'LOAD_USER_FAILURE',

	ADD_TICKET:         'ADD_TICKET',
	ADD_TICKET_SUCCESS: 'ADD_TICKET_SUCCESS',
	ADD_TICKET_FAILURE: 'ADD_TICKET_FAILURE',

	EDIT_TICKET:         'EDIT_TICKET',
	EDIT_TICKET_SUCCESS: 'EDIT_TICKET_SUCCESS',
	EDIT_TICKET_FAILURE: 'EDIT_TICKET_FAILURE',

	REMOVE_TICKET:         'REMOVE_TICKET',
	REMOVE_TICKET_SUCCESS: 'REMOVE_TICKET_SUCCESS',
	REMOVE_TICKET_FAILURE: 'REMOVE_TICKET_FAILURE',

	SET_TICKET_ACTIVE: 'SET_TICKET_ACTIVE',

	AUTH_FAILURE:   'AUTH_FAILURE',
	CHANGE_SETTING: 'CHANGE_SETTING',

	LOGIN:         'LOGIN',
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAILURE: 'LOGIN_FAILURE',

	LOGOUT:         'LOGOUT',
	LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
	LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}
