'use strict';

/**
 * Defines 'action' constants.
 */
module.exports = {
	LOAD_TICKETS:         'LOAD_TICKETS',
	LOAD_TICKETS_SUCCESS: 'LOAD_TICKETS_SUCCESS',
	LOAD_TICKETS_FAILURE: 'LOAD_TICKETS_FAILURE',

	EDIT_TICKET:         'EDIT_TICKET',
	EDIT_TICKET_SUCCESS: 'EDIT_TICKET_SUCCESS',
	EDIT_TICKET_FAILURE: 'EDIT_TICKET_FAILURE',
}
